### ISSUE TITLE
Screen selector displays incorrect screen

### ISSUE THREAD

**Issue by nevadascout** [TypicalDarkness/GTA-Gadget#1]
Had a look at your code, and where you call `check2_click`, you're setting the screen ID to 1 when it should be 2, and on `check3_click`, you're setting the screen ID to 2 when it should be 1.

If you were to rename `check2` to `MonitorMiddle` and the same for `check3` and `check4` you could avoid an issue like this in the future :)

![gta-gadget-bug](https://cloud.githubusercontent.com/assets/377089/6766190/d9c0b9fc-cff3-11e4-82b0-364495f2470d.png)

**Comment by TypicalDarkness** [comment]
It depends on whether your secondary screen is left or right to the primary screen. check2=primary screen; check3=second screen; check4=third screen. I'll try to fix this

**Comment by nevadascout** [comment]
Good point. I have the left as my primary monitor.

You could try using the `DeviceName` property of `Screen` ->

![gta-gadget-devicename](https://cloud.githubusercontent.com/assets/377089/6766359/aebcc054-cffb-11e4-88e3-562968464ee1.png)

**Comment by TypicalDarkness** [comment]
Ok, I think i fixed it. If the .bounds of Screen(1)(second screen) are <0, the second screen is left to the primary one.



    Public Sub movegadget(screenid As Integer, locationid As Integer)
        checkscreens()
        expanded.BringToFront()
        cxt.BringToFront()
        Dim numberofmonitors As Integer = Screen.AllScreens.Length




        If Not (Screen.AllScreens.Length = 2 And Screen.AllScreens(0).Bounds.X > 0) Then
            If screenid = 1 Then
                screenid = 2
            Else
                screenid = 1
            End If
        End If
        Dim Screenx As Screen = Screen.AllScreens(screenid - 1)
        Select Case locationid
            Case 1
                cxt.Location = New Point(Screenx.Bounds.X, -40)
                expanded.Location = New Point(Screenx.Bounds.X, 32)
                expanded.Panel6.Location = New Point(1, -13)
            Case 2
                cxt.Location = New Point(Screenx.Bounds.X + Screenx.Bounds.Width / 2 - cxt.Width / 2, -40)
                expanded.Location = New Point(Screenx.Bounds.X + Screenx.Bounds.Width / 2 - expanded.Width / 2, 32)
                expanded.Panel6.Location = New Point(233, -13)
            Case 3
                cxt.Location = New Point(Screenx.Bounds.X + Screenx.Bounds.Width - cxt.Width, -40)
                expanded.Location = New Point(Screenx.Bounds.X + Screenx.Bounds.Width - expanded.Width, 32)
                expanded.Panel6.Location = New Point(463, -13)
        End Select



    End Sub

**Comment by nevadascout** [comment]
This now works for me. I also tested it with making my right monitor the primary screen and it still works so good job :)

One thing thing though:
    If screenid = 1 Then
        screenid = 2
    Else
        screenid = 1
    End If

When you hit the else block, if `screenid` is not equal to 1, you'll set it to 1. So this will break for people who have three screens.

A better way might be to pass in the correct number from the calling function instead of changing it in here

**Comment by TypicalDarkness** [comment]
No, because the whole think will only happen, when there're 2 screens:
 
 If Screen.AllScreens.Length = 2

**Comment by nevadascout** [comment]
You've actually put `If Not` instead of `If` :)

`If Not (Screen.AllScreens.Length = 2 And Screen.AllScreens(0).Bounds.X > 0) Then`

**Comment by TypicalDarkness** [comment]
Yes. I changed it 5 mins. after I posted it to

If Screen.AllScreens.Length = 2 And Not Screen.AllScreens(0).Bounds.X > 0 Then

**Comment by nevadascout** [comment]
Yeah, I saw :)

**Comment by TypicalDarkness** [comment]
I'm no to Github How can I display code like this:
![code](https://cloud.githubusercontent.com/assets/11584285/6766951/8e9d48a0-d01b-11e4-9380-ea0421d1e6a9.PNG)

**Comment by TypicalDarkness** [comment]
´test´

**Comment by TypicalDarkness** [comment]
`test`

**Comment by nevadascout** [comment]
This page has a load of info about the "Markdown" format that it uses :)

https://guides.github.com/features/mastering-markdown/

**Comment by nevadascout** [comment]
Also, you might want to make your commit messages more descriptive :)

So, a quick description of what you've changed in that commit eg "fixed bug with selecting screens"

You can actually make a commit message like "fixes #1" and it'll close the issue with the ID of 1 :)

**Comment by TypicalDarkness** [comment]
OK :)
Thanks for all the help btw.

**Comment by nevadascout** [comment]
No worries :)

You should really look at C# instead of Visual Basic though - C# is much more superior in just about every way :P

**Comment by TypicalDarkness** [comment]
Thanks for your advice :D I tried C# and it's just awesome :DD

**Comment by nevadascout** [comment]
Awesome! If you need any help, just ask :)
